FROM langflowai/langflow:1.7.3

COPY flows/ /flows/

ENV LANGFLOW_LOAD_FLOWS_PATH=/flows
ENV LANGFLOW_HOST=0.0.0.0
ENV LANGFLOW_PORT=10000
ENV LANGFLOW_FALLBACK_TO_ENV_VAR=true
ENV LANGFLOW_VARIABLES_TO_GET_FROM_ENVIRONMENT=OPENAI_API_KEY,LF_OPENAI_KEY

EXPOSE 10000

CMD ["sh", "-c", "langflow run --host 0.0.0.0 --port ${PORT:-10000}"]
